### PR TITLE
Support stableperl

### PR DESCRIPTION
**Pull request by moznion**

### CODE REVIEW

**Comment by tokuhirom** [comment]
this p-r needs docs!

**Comment by moznion** [comment]
Done!

**Comment by miyagawa** [comment]
Nothing seems wrong with this patch, but plenv supports arbitrary URLs already:

```
plenv install --as=5.22.0-schmorp http://stableperl.schmorp.de/dist/stableperl-5.22.0-1.001.tar.gz
```

**Comment by miyagawa** [comment]
I don't think there's any strong argument to special case stableperl like this in Perl::Build and I recommend to revert this change.

**Pull request merged**
