### PR TITLE
Modify from HTTP::Tiny to HTTP::Tinyish

### PR DESCRIPTION
**Pull request by AnaTofuZ**
Moved to HTTP::Tinyish because HTTPS is used for metacpan access.

### CODE REVIEW

**Comment by skaji** [comment]
Could you add verify_SSL => 1 to HTTP::Tinyish->new?

**Comment by miyagawa** [comment]
👍

**Comment by skaji** [comment]
@tokuhirom Can we merge this?

**Comment by AnaTofuZ** [comment]
I solved the conflict

**Comment by tokuhirom** [comment]
@skaji you can merge any pr in this repo without notice~

**Comment by tokuhirom** [comment]
(Added @skaji as a co-maint on PAUSE

**Comment by skaji** [comment]
@tokuhirom Thanks!

**Pull request merged**
